"""
Data model for the static code map generated by `serena project export-code-map`.
"""

from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Any, Literal, Self

from solidlsp.ls_types import SymbolKind

EXTERNAL_LANGUAGE_SERVER = "external"
"""Pseudo language server identifier used for symbols that could not be resolved within the project."""

INCLUDED_SYMBOL_KINDS = (
    SymbolKind.Namespace,
    SymbolKind.Package,
    SymbolKind.Module,
    SymbolKind.Class,
    SymbolKind.Interface,
    SymbolKind.Struct,
    SymbolKind.Enum,
    SymbolKind.Function,
    SymbolKind.Method,
    SymbolKind.Constructor,
)
"""Symbol kinds included in the code map by default (low-level symbols like variables and fields are excluded)."""

CALLABLE_SYMBOL_KINDS = (SymbolKind.Function, SymbolKind.Method, SymbolKind.Constructor)
"""Symbol kinds for which outgoing calls are requested."""

TYPE_SYMBOL_KINDS = (SymbolKind.Class, SymbolKind.Interface, SymbolKind.Struct, SymbolKind.Enum)
"""Symbol kinds for which supertypes are requested."""

DOCUMENTED_SYMBOL_KINDS = (
    SymbolKind.Class,
    SymbolKind.Interface,
    SymbolKind.Struct,
    SymbolKind.Enum,
    SymbolKind.Function,
    SymbolKind.Method,
    SymbolKind.Constructor,
)
"""Symbol kinds for which quick info (hover) is requested."""

OWNER_SYMBOL_KINDS = (
    SymbolKind.Class,
    SymbolKind.Interface,
    SymbolKind.Struct,
    SymbolKind.Module,
    SymbolKind.Namespace,
)
"""Symbol kinds that can serve as the owner of a callable for CLASS_DEPENDS_ON aggregation."""

EdgeType = Literal["CONTAINS", "CALLS", "TYPE_SUPERTYPE", "CLASS_DEPENDS_ON"]
EdgeResolution = Literal["documentSymbol", "callHierarchy", "typeHierarchy", "derived"]
CoverageStatus = Literal["supported", "unsupported", "partial", "not_attempted"]


@dataclass(frozen=True)
class SourcePosition:
    line: int
    character: int

    @classmethod
    def from_lsp(cls, position: Mapping[str, Any]) -> Self:
        return cls(line=position["line"], character=position["character"])

    def to_dict(self) -> dict[str, int]:
        return {"line": self.line, "character": self.character}


@dataclass(frozen=True)
class SourceRange:
    start: SourcePosition
    end: SourcePosition

    @classmethod
    def from_lsp(cls, range_dict: Mapping[str, Any]) -> Self:
        return cls(start=SourcePosition.from_lsp(range_dict["start"]), end=SourcePosition.from_lsp(range_dict["end"]))

    def to_dict(self) -> dict[str, dict[str, int]]:
        return {"start": self.start.to_dict(), "end": self.end.to_dict()}

    def sort_key(self) -> tuple[int, int, int, int]:
        return (self.start.line, self.start.character, self.end.line, self.end.character)


@dataclass
class CodeMapSymbol:
    id: str
    language_server: str
    name: str
    name_path: str
    kind: str
    relative_path: str | None
    selection_range: SourceRange | None
    body_range: SourceRange | None
    parent_id: str | None
    child_ids: list[str] = field(default_factory=list)
    quick_info_raw: str | None = None
    signature: str | None = None
    documentation: str | None = None
    is_external: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "language_server": self.language_server,
            "name": self.name,
            "name_path": self.name_path,
            "kind": self.kind,
            "relative_path": self.relative_path,
            "selection_range": self.selection_range.to_dict() if self.selection_range else None,
            "body_range": self.body_range.to_dict() if self.body_range else None,
            "parent_id": self.parent_id,
            "child_ids": self.child_ids,
            "quick_info_raw": self.quick_info_raw,
            "signature": self.signature,
            "documentation": self.documentation,
            "is_external": self.is_external,
        }


@dataclass
class CodeMapEdge:
    type: EdgeType
    source: str
    target: str
    source_ranges: list[SourceRange] = field(default_factory=list)
    count: int = 1
    resolution: EdgeResolution = "derived"

    def to_dict(self) -> dict[str, Any]:
        return {
            "type": self.type,
            "source": self.source,
            "target": self.target,
            "source_ranges": [r.to_dict() for r in sorted(self.source_ranges, key=SourceRange.sort_key)],
            "count": self.count,
            "resolution": self.resolution,
        }


@dataclass
class CodeMapDiagnostic:
    level: Literal["info", "warning", "error"]
    phase: str
    message: str
    language_server: str | None = None
    relative_path: str | None = None
    symbol_id: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "level": self.level,
            "phase": self.phase,
            "language_server": self.language_server,
            "relative_path": self.relative_path,
            "symbol_id": self.symbol_id,
            "message": self.message,
        }


@dataclass
class LanguageServerCoverage:
    """Per-language-server statistics on what could be retrieved during the export."""

    document_symbols: CoverageStatus = "not_attempted"
    hover: CoverageStatus = "not_attempted"
    call_hierarchy: CoverageStatus = "not_attempted"
    type_hierarchy: CoverageStatus = "not_attempted"
    hover_symbols_attempted: int = 0
    hover_symbols_resolved: int = 0
    callable_symbols_attempted: int = 0
    callable_symbols_resolved: int = 0
    type_symbols_attempted: int = 0
    type_symbols_resolved: int = 0
    call_edges: int = 0
    errors: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "document_symbols": self.document_symbols,
            "hover": self.hover,
            "call_hierarchy": self.call_hierarchy,
            "type_hierarchy": self.type_hierarchy,
            "hover_symbols_attempted": self.hover_symbols_attempted,
            "hover_symbols_resolved": self.hover_symbols_resolved,
            "callable_symbols_attempted": self.callable_symbols_attempted,
            "callable_symbols_resolved": self.callable_symbols_resolved,
            "type_symbols_attempted": self.type_symbols_attempted,
            "type_symbols_resolved": self.type_symbols_resolved,
            "call_edges": self.call_edges,
            "errors": self.errors,
        }


@dataclass
class CodeMap:
    """The complete in-memory representation of a generated code map."""

    project_name: str
    symbols_by_id: dict[str, CodeMapSymbol] = field(default_factory=dict)
    edges: list[CodeMapEdge] = field(default_factory=list)
    diagnostics: list[CodeMapDiagnostic] = field(default_factory=list)
    coverage: dict[str, LanguageServerCoverage] = field(default_factory=dict)
    dropped_diagnostics: int = 0

    def sorted_symbols(self) -> list[CodeMapSymbol]:
        return sorted(self.symbols_by_id.values(), key=lambda s: s.id)

    def sorted_edges(self) -> list[CodeMapEdge]:
        return sorted(self.edges, key=lambda e: (e.type, e.source, e.target))

    def edges_by_type(self, edge_type: EdgeType) -> list[CodeMapEdge]:
        return [e for e in self.sorted_edges() if e.type == edge_type]

    def incoming_edges(self, edge_type: EdgeType) -> dict[str, list[CodeMapEdge]]:
        """Reverse lookup: maps target symbol id to the (sorted) edges of the given type pointing to it."""
        result: dict[str, list[CodeMapEdge]] = {}
        for edge in self.sorted_edges():
            if edge.type == edge_type:
                result.setdefault(edge.target, []).append(edge)
        return result

    def outgoing_edges(self, edge_type: EdgeType) -> dict[str, list[CodeMapEdge]]:
        """Maps source symbol id to the (sorted) edges of the given type originating from it."""
        result: dict[str, list[CodeMapEdge]] = {}
        for edge in self.sorted_edges():
            if edge.type == edge_type:
                result.setdefault(edge.source, []).append(edge)
        return result
